# -*- coding: utf-8 -*-
"""Python 1 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19xSeOfGlhZHe8ZCpHtyAJE39AtjdhSfz
"""

a="Pranjal"
print(a)
b=3
print(b)
c="3"
print(c)
# 3 is number
#"3" is a string
s=22/7
print(s)
x,y=10,5
print("Addition=",x+y)
print("Subtraction=",x-y)
print("Multiplication=",x*y)
print("Division=",x/y)
print("Power=",x**y)
print("Modulus=",x%y)
print("Floor Division=",x//y)
print("sqrt=",s)



